---
title: "Untitled"
output: html_document
date: "2024-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Introduction 

This is my experiment on helicopters. 

## Experimental Design 

```{r}
library(dplyr)

wing_length = c(4, 5)
body_length = c(6, 7)
body_width = c(4,5)
drop_style= c("pinched", "dropped")
paper_clip = c("yes", "no")


# Generate treatment combinations
treatment_combinations <- expand.grid(
  Wing_Length = wing_length,
  Body_Length = body_length,
  Body_Width = body_width,
  Drop_Style = drop_style,
  Paper_Clip = paper_clip
)

# replicate design
replicates = 1
replicated_design = replicates

# Randomize design
set.seed(123)  # For reproducibility
randomized_design <- treatment_combinations %>%
  mutate(Random_Number = runif(nrow(.))) %>%
  arrange(Random_Number) %>%
  select(-Random_Number)


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
1-pi(4306.2 - 4306.2, 11999, 11996)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
